
version: '3.1'

services: 
  backend:
    build: ./covidmetrics
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": 8000
        }'
    ports: 
      - 6767:8000
    restart: on-failure
